export default {
    SET_ACCOUNT_TYPE_LIST: 'signIn/SET_ACCOUNT_TYPE_LIST',
    SET_ACCOUNT_TYPE_DATA: 'signIn/SET_ACCOUNT_TYPE_DATA',
    SET_USER_TOKEN: 'signIn/SET_USER_TOKEN',
    SET_USER_DETAILS: 'signIn/SET_USER_DETAILS'
}