export default {
  GRAPHQL_REQUEST: 'api/GRAPHQL_REQUEST',
  GRAPHQL_START: 'api/GRAPHQL_START',
  GRAPHQL_END: 'api/GRAPHQL_END',
  GRAPHQL_ERROR: 'api/GRAPHQL_ERROR',
  GRAPHQL_CLEAR_ERROR: 'api/GRAPHQL_CLEAR_ERROR',
};
